image: golang:1.19

# DinD service is required for Testcontainers
services:
  - name: docker:dind
    # explicitly disable tls to avoid docker startup interruption
    command: ["--tls=false"]

variables:
  # Instruct Testcontainers to use the daemon of DinD, use port 2735 for non-tls connections.
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

stages:
  - test

.go-cache:
  variables:
    GOMODCACHE: $CI_PROJECT_DIR/.cache
  before_script:
    - mkdir -p .cache
  cache:
    paths:
      - .cache

test_app:
  stage: test
  extends: .go-cache
  tags:
    - gitlab-org-docker
  script:
    - make test-app
