name: Main pipeline

on: [ push, pull_request ]

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.sha }}"
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.19.x, 1.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    env:
      TESTCONTAINERS_RYUK_DISABLED: "false"
    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Test in ./app
        run: |
          make test-app
